---

- hosts: localhost
  become: true
  tasks:

  - name: Create cloudru user
    ansible.builtin.user:
      name: cloudru
      password: "{{ 'cloudpass' | password_hash('sha512') }}"
      createhome: true
      groups:
        - sudo

  - name: Create a /home/cloudru/.ssh directory
    ansible.builtin.file:
      path: /home/cloudru/.ssh/
      state: directory

  - name: Create a /home/cloudru/.ssh/authorized_keys file and add sshpub key
    lineinfile:
      dest: /home/cloudru/.ssh/authorized_keys
      line: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCfrfE0OluoNHb5dOpV4RpWmVXvMBWc17kaM7DDjCm7romNQMDX95i5Fc67Q3c47pvrm/qi/ZqsCeqNdLl5+VV41rVz701Pj/UUr2FZpIm80Ur0iM1DFy81GKo/lS1INopqdd4KvUnM2d8yqfJSm9m5Cq7AM9S0mqObuMayfqNR4YcOlm9fnEMqhrSWbBVvdghPNiBzs7T9RzEq/0w8rs743tCF7MICv72fdgYadrGlxFsFWSujwZXQLI4VUSxKirJBCUgfR0u84gZK/wUzJ4EPqMichniTf24AsvidozUHWMDmQ+pUaBTyxjD5egi8LcV0EHH4feHwzacA2gyGbOtFK3wpa/dgE1yvPTkPKnccIXKnbel0mfxfsBVkclc5/DnczmrdaGrX5DCrQbI+HO4lhr4KzAm/pw6qfLcw8KjCdVKsnCRXykdat8KUwNAeolknRWdKDqdsbyXBj+ePMTlMR8YmoBj9znYWwOnAAyu56utiteL0oq9YPkb7ZGF5ZOE='
      insertafter: EOF
      create: True


  - name: Update all apt packages
    apt: upgrade=dist force_apt_get=yes

  - name: Install ssh-server
    apt: name=openssh-server

  - name: Enable shh login with pubkey
    lineinfile:
      dest=/etc/ssh/sshd_config
      regexp='PubkeyAuthentication'
      insertbefore=BOF
      line='PubkeyAuthentication yes'

  - name: Disable shh login for root
    lineinfile:
      dest=/etc/ssh/sshd_config
      regexp='^#PermitRootLogin'
      insertbefore=BOF
      line='PermitRootLogin no'

  - name: Enable the ssh service
    command: systemctl restart ssh
